name: Auto Tag from Merge

on:
  push:
    branches:
      - main
      - uat
      - develop

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VER=$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' VERSION || echo "")
          BRANCH=$(echo "${GITHUB_REF##*/}")
          PREFIX=${BRANCH}
          echo "tag=${PREFIX}-${VER}" >> $GITHUB_OUTPUT

      - name: Push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}
