name: Docker CI/CD

on:
  workflow_run:
    workflows: ["Auto Tag from Merge"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
      docker_tag: ${{ steps.env.outputs.docker_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags and extract latest
        id: tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-creatordate | grep -E '^(main|uat|develop)-v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set tag branch type
        id: env
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          BRANCH_NAME=$(echo "$TAG" | cut -d'-' -f1)
          echo "env=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            apexdev23/sms-gw:${{ steps.env.outputs.docker_tag }}
            apexdev23/sms-gw:latest

  deploy:
    needs: build-and-push
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - env: main
            runner: self-hosted-main
          - env: uat
            runner: self-hosted-uat
          - env: develop
            runner: self-hosted-dev

    steps:
      - uses: actions/checkout@v4

      - name: Skip unless matching environment
        if: ${{ needs.build-and-push.outputs.env != matrix.env }}
        run: echo "Skipping deploy for env ${{ matrix.env }}"

      - name: Docker login on server
        if: ${{ needs.build-and-push.outputs.env == matrix.env }}
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        if: ${{ needs.build-and-push.outputs.env == matrix.env }}
        run: |
          cd ~/sms-gw
          ./deploy.sh "${{ needs.build-and-push.outputs.docker_tag }}"
