name: Docker CI/CD

on:
  push:
    tags:
      - 'main-*'
      - 'uat-*'
      - 'develop-*' 
  workflow_run:
    workflows: ["Auto Tag from Merge"]
    types:
      - completed

permissions:
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag or branch
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "docker_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
            echo "is_version=true" >> $GITHUB_OUTPUT
          else
            BRANCH=${GITHUB_REF##*/}
            echo "docker_tag=$BRANCH" >> $GITHUB_OUTPUT
            echo "is_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            apexdev23/sms-gw:${{ steps.vars.outputs.docker_tag }}
            apexdev23/sms-gw:latest

  deploy-main:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: [self-hosted, main]
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker login on server
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          cd ~/sms-gw
          ./deploy.sh "$TAG_NAME"

  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    needs: build-and-push
    runs-on: [self-hosted, uat]
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker login on server
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          cd ~/sms-gw
          ./deploy.sh "$TAG_NAME"

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: build-and-push
    runs-on: [self-hosted, dev]
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker login on server
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          cd ~/sms-gw
          ./deploy.sh "$TAG_NAME"
  
