name: Docker Image CI

on:
  push:
    tags:
      - 'v*' 
    branches: 
      - main
      - develop
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag to deploy (commit SHA or version)"
        required: false
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag or branch
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
            echo "docker_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
            echo "is_version=true" >> $GITHUB_OUTPUT
          else
            BRANCH=${GITHUB_REF##*/}
            echo "docker_tag=$BRANCH" >> $GITHUB_OUTPUT
            echo "is_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            apexdev23/sms-gw:${{ steps.vars.outputs.docker_tag }}
            apexdev23/sms-gw:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker login on server
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        run: |
          cd ~/sms-gw
          ./deploy.sh ${{ github.event.inputs.tag || steps.vars.outputs.docker_tag }}

  rollback:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Rollback to specific tag
        run: |
          cd ~/sms-gw
          echo "Rolling back to tag: ${{ github.event.inputs.tag }}"
          ./deploy.sh ${{ github.event.inputs.tag }}

  collect-logs:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Collect logs folder
        run: |
          cd ~/sms-gw
          tar -czf logs.tar.gz logs || echo "No logs directory found"
      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-logs
          path: ~/sms-gw/logs.tar.gz
