name: CI/CD UAT Deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: uat
  cancel-in-progress: true

jobs:
  prepare-candidate:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.collect.outputs.has_prs }}
      prs: ${{ steps.collect.outputs.prs }}
      docker_tag: ${{ steps.version.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure jq + gh
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Find PRs marked for UAT
        id: collect
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
      
          git fetch --tags origin
          LAST_TAG=$(git tag --sort=-creatordate | grep '^uat-v' | head -n1 || true)
      
          # Get all PRs with promote:uat label
          gh pr list --repo "$REPO" --state merged --label "promote:uat" \
            --json number,mergeCommit,baseRefName | jq -r '.[] | select(.baseRefName == "develop") | "\(.number) \(.mergeCommit.oid)"' > all_uat_prs.txt
      
          if [ ! -s all_uat_prs.txt ]; then
            echo "prs=" >> "$GITHUB_OUTPUT"
            echo "has_prs=false" >> "$GITHUB_OUTPUT"
            echo "No PRs found with promote:uat label."
            exit 0
          fi
      
          # Filter out PRs already in last UAT deployment
          > prs_to_deploy.txt
          > commits.txt
          
          while read line; do
            [ -z "$line" ] && continue
            PR_NUMBER=$(echo "$line" | cut -d' ' -f1)
            MERGE_COMMIT=$(echo "$line" | cut -d' ' -f2)
            
            if [ -n "$LAST_TAG" ]; then
              # Check if this PR's merge commit is in the last tag's history
              if git tag --contains "$MERGE_COMMIT" | grep -q "^uat-v"; then
                echo "PR #$PR_NUMBER already deployed in previous UAT version, skipping"
                continue
              fi
            fi
            
            echo "PR #$PR_NUMBER needs deployment"
            echo "$PR_NUMBER" >> prs_to_deploy.txt
            echo "$MERGE_COMMIT" >> commits.txt
          done < all_uat_prs.txt
      
          if [ ! -s prs_to_deploy.txt ]; then
            echo "prs=" >> "$GITHUB_OUTPUT"
            echo "has_prs=false" >> "$GITHUB_OUTPUT"
            echo "No new PRs found for UAT promotion since last deployment."
            exit 0
          fi
      
          PRS=$(paste -sd, prs_to_deploy.txt)
          echo "prs=$PRS" >> "$GITHUB_OUTPUT"
          echo "has_prs=true" >> "$GITHUB_OUTPUT"
          echo "PRs to promote: $PRS"
      
          # Save PR numbers to a file for later use
          echo "$PRS" > pr_numbers.txt
      
          echo "Collected commits:"
          cat commits.txt

      - name: Build uat-candidate branch using GitHub API
        if: ${{ steps.collect.outputs.has_prs == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          
          # Create a new branch from uat
          git fetch origin uat
          git checkout -B uat-candidate origin/uat
          
          # For each PR, create a merge commit using GitHub API
          while read commit; do
            [ -z "$commit" ] && continue
            
            # Find the PR number from the commit
            PR_NUMBER=$(gh api -X GET "repos/$REPO/commits/$commit/pulls" -q '.[0].number' || echo "")
            
            if [ -n "$PR_NUMBER" ]; then
              echo "Merging PR #$PR_NUMBER ($commit)"
              
              # Use GitHub API to create a proper merge
              gh pr merge $PR_NUMBER --merge --subject "Merge PR #$PR_NUMBER to UAT" --body "Automated UAT deployment"
              
              # Pull the changes
              git pull origin uat-candidate
            else
              echo "Could not find PR for commit $commit, applying directly"
              if git show --no-patch --format="%P" "$commit" | grep -q " "; then
                git cherry-pick -x -m 1 "$commit" || git cherry-pick --skip
              else
                git cherry-pick -x "$commit" || git cherry-pick --skip
              fi
            fi
          done < commits.txt
          
          git push origin uat-candidate --force

      - name: Set Docker tag
        id: version
        if: ${{ steps.collect.outputs.has_prs == 'true' }}
        run: |
          LATEST=$(git tag --sort=-creatordate | grep '^uat-v' | head -n1 || echo "uat-v0.0.0")
          BASE="${LATEST#uat-v}"
          IFS=. read -r MAJOR MINOR PATCH <<< "$BASE"
          PATCH=$((PATCH+1))
          NEW="uat-v$MAJOR.$MINOR.$PATCH"
          echo "docker_tag=$NEW" >> "$GITHUB_OUTPUT"
          echo "Using Docker tag: $NEW"

  build-and-push:
    needs: prepare-candidate
    if: ${{ needs.prepare-candidate.outputs.should_deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: uat-candidate
          fetch-depth: 0

      - name: Download PR numbers artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-numbers
          path: .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            apexdev23/sms-gw:${{ needs.prepare-candidate.outputs.docker_tag }}
            apexdev23/sms-gw:latest-uat

  deploy-uat:
    needs: build-and-push
    runs-on: [self-hosted, uat]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download PR numbers artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-numbers
          path: .

      - name: Docker login on server
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy App
        run: |
          cd ~/sms-gw
          ./deploy.sh ${{ needs.prepare-candidate.outputs.docker_tag }}

      - name: Configure Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fast-forward uat to candidate
        if: ${{ success() }}
        run: |
          git fetch origin uat uat-candidate
          git checkout uat
          git merge origin/uat-candidate --ff-only
          git push origin uat

          VERSION=${{ needs.prepare-candidate.outputs.docker_tag }}
          git tag -f "$VERSION"
          git push origin "$VERSION" --force

      - name: Remove promote:uat labels
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          PRS=$(cat pr_numbers.txt)
          if [ -n "$PRS" ]; then
            IFS=',' read -ra arr <<< "$PRS"
            for num in "${arr[@]}"; do
              echo "Removing promote:uat label from PR #$num"
              gh pr edit "$num" --remove-label "promote:uat" --repo "$REPO" || \
                echo "Failed to remove label from PR #$num (might already be removed)"
            done
          else
            echo "No PR numbers found to remove labels from"
          fi
